name: CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-ml-app:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-ml-app:latest

      - name: Deploy to EC2 Kubernetes (Rolling Update)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling updated Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/weather-ml-app:latest
            
            echo "Applying Kubernetes manifests..."
            kubectl apply -f weather-ml-app/k8s/

            echo "Triggering rolling update..."
            kubectl rollout restart deployment/weather-ml-app-deployment

            echo "Waiting for deployment to finish..."
            kubectl rollout status deployment/weather-ml-app-deployment --timeout=120s

            echo "Deployment complete!"

